base_global_planner: global_planner/GlobalPlanner
GlobalPlanner:
  cost_factor: 0.55
  lethal_cost: 253
  neutral_cost: 66
  orientation_mode: 0
  orientation_window_size: 1
  publish_potential: true
  default_tolerance: 0.2