local_costmap:
  plugins:
  - {name: 2d_obstacles, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  global_frame: obstacle_bot_odom
  robot_base_frame: obstacle_bot_base_footprint
  update_frequency: 10.0
  publish_frequency: 5.0
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.06
