obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.55

# Standard pioneer3dx footprint (meters)
footprint: [ [0.254, -0.0508], [0.1778, -0.0508], [0.1778, -0.1778], [-0.1905, -0.1778], [-0.254, 0], [-0.1905, 0.1778], [0.1778, 0.1778], [0.1778, 0.0508], [0.254, 0.0508] ]

# Generous footprint for safety
# footprint: [ [0.16, 0.19], [0.26, 0.0], [0.16, -0.19], [-0.18, -0.19], [-0.26, 0.0], [-0.18, 0.19] ]

footprint_padding: 0.0

transform_tolerance: 0.2
map_type: costmap

2d_obstacles:
  observation_sources: laser
  laser: {data_type: LaserScan, sensor_frame: pioneer/hokuyo_front_link, topic: /pioneer/frontscan_filtered, marking: true, clearing: true, expected_update_rate: 0.2}
